import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title>BeeCat Creative</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home">
        <div className="home__logo">
          <img src='/images/beecat-logo.jpg' alt="BeeCat Creative | Logo" />
        </div>
      </main>
    </div>
  )
}
