import Head from 'next/head'
import Image from 'next/image'

import ContactForm from '../components/ContactForm'

export default function Home() {
  return (
    <div className="main-container">
      <Head>
        <title>BeeCat Creative</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="home">
        <div className="home__logo">
          <img src='/images/beecat-logo.png' alt="BeeCat Creative | Logo" />
        </div>
        <div className="home__inner">
          <div className="home-header">
            <h1 className="bold-header">The hype is real</h1>
            <h2 className="bold-header-2">Website coming soon</h2>
            <div className="divider"></div>
            <h1 className="light-header">We're not "here" but we're still "here".</h1>
            <h1 className="light-header">Drop us a line.</h1>
          </div>
          <div className="home-form">
            <ContactForm />
          </div>
        </div>
      </main>
    </div>
  )
}
